### PR TITLE
Update ctr.csv

### PR DESCRIPTION
**Pull request by K1rbYat1Na**
Added the Inazuma Eleven GO series games.

### CODE REVIEW

**Comment by ninstar** [comment]
Do you have the icons for these games?

**Comment by K1rbYat1Na** [comment]
Yes, but they're not upscaled yet.

**Comment by ninstar** [comment]
You don't have to worry about upscaling them, you can link them here if you want.

**Comment by K1rbYat1Na** [comment]
Here. They're from eShop.
_**Inazuma Eleven GO**_:
([_**Shine**_ (izelvngo1s)](https://img-eshop.cdn.nintendo.net/i/49f75859a7c85203453788451482a04eeb6ffe38957de908fd13aa059e557e96.jpg)/[_**Dark**_ (izelvngo1d)](https://img-eshop.cdn.nintendo.net/i/fe67a5b3f77e7ebca724c447a48fac51ee909a0a0c5a52b920594f76fa4fd09f.jpg))
_Inazuma Eleven GO 2: Chrono Stone_:
([_**Neppuu**_ (izelvngo2n)](https://img-eshop.cdn.nintendo.net/i/13e03cc0e044b3f1439b6025c6f3af3cb18689ec1bf8c18e274c4ac4db0f2144.jpg)/[_**Raimei**_ (izelvngo2r)](https://img-eshop.cdn.nintendo.net/i/5721a95e8fbf085c7d67d9639638ec21bc8facbd7d41e22e3d2514fe65663b91.jpg))
_Inazuma Eleven GO: Galaxy_:
([_**Big Bang**_ (izelvngo3b)](https://img-eshop.cdn.nintendo.net/i/43c361a3f6696ab48eeb934c6dfa5a06694d8c71b8a1c15d7532510ba391c509.jpg)/[_**Supernova**_ (izelvngo3s)](https://img-eshop.cdn.nintendo.net/i/aa20c3d031c72e990f8fed0a9d9483f5cabf92dacff7c14a799f4b0e2dd24f6f.jpg))
[_**Inazuma Eleven 1-2-3!!: Endou Mamoru Densetsu**_ (izelvn123)](https://img-eshop.cdn.nintendo.net/i/9275f910e26ffef05c2f61806f77bb59e279f8a1251e3bae6393d98dfb63f3a4.jpg)

**Comment by ninstar** [comment]
Done.

**Pull request merged**
