### PR TITLE
Update titles_nswitch.csv

### PR DESCRIPTION
**Pull request by daylightEX**
Added Shin Megami Tensei V

Icon link: https://i.redd.it/r8ympcwg6vw71.jpg

### CODE REVIEW

**Comment by ninstar** [comment]
Sorry but the icon doesn't seem match the aspect ratio for all other icons, can you provide another source?
As mentioned in the readme, icons need to be at least 512x512 (1:1 aspect ratio).

**Comment by daylightEX** [comment]
Is this better?

https://64.media.tumblr.com/8e8f60026f26236a6fb3c5d29acab85a/10c1b261e0ca9237-e1/s1280x1920/95d6691f95af9720d5e0e42754a4aba1e836ee03.png

**Comment by ninstar** [comment]
Just a question, is this the official icon for the game?

**Comment by daylightEX** [comment]
No

**Comment by ninstar** [comment]
Closing this pull request since someone submitted the correct icons.

**Pull request closed without merging**
