### PR TITLE
added some applets and menu applications

### PR DESCRIPTION
**Pull request by dwyazzo90**

### CODE REVIEW

**Comment by davidsosa2022** [comment]
forgot to add ,, to Wii U Menu and Software/Data Transfer

**Comment by ninstar** [comment]
Do you have the icons for these entries?

**Comment by davidsosa2022** [comment]
> Do you have the icons for these entries?

I think they are all on the icon folder here

**Comment by ninstar** [comment]
> > Do you have the icons for these entries?
> 
> I think they are all on the icon folder here

Which folder exactly?

**Comment by davidsosa2022** [comment]
https://drive.google.com/file/d/1wuJufR5vFR0toGrkj61ogk57ThJ1fbAD/view?usp=sharing, on the Unused icon folder

**Comment by ninstar** [comment]
The assets seem unavailable, you can open a new pull request if you wish.

**Pull request closed without merging**
